#!/usr/bin/env bash
# Disable strict host key checking
export SCP_OPTIONS="-o StrictHostkeyChecking=no"

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp $SCP_OPTIONS -i "$4" "$1" "$3@$2":"~/"
fi
