#!/usr/bin/env bash
# config ngnix server to listen to port 80 in a more precise way.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
