#!/usr/bin/env bash
# displays numbers or bad luck for bad luck numbers

counter=1
while [ $counter -lt 21 ]
do
	echo "$counter"
	case $counter in 
		4) 
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((counter++))
done
