#!/usr/bin/env bash

LOCAL="127.0.0.2"
FACEBOOK="8.8.8.8"

if [ -f "/etc/hosts" ]; then
	cp /etc/hosts ~/hosts.new
	sed -i "s/^127.0.0.1.*/$LOCAL localhost/" /etc/hosts
	cp -f ~/hosts/new /etc/hosts
fi
