#!/usr/bin/env bash
# change the /etc/hosts file

LOCAL="127.0.0.2"
FACEBOOK="8.8.8.8"

cp /etc/hosts ~/hosts.new
sed -i "s/^127.0.0.1.*/$LOCAL localhost/" /etc/hosts
echo "$FACEBOOK	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
